import { useEffect, useRef, useState } from 'react';
import { Contract, ZeroAddress, isAddress } from 'ethers';
import { ArrowUpRight, Check, Download, LoaderCircle, Copy, LockKeyhole, Layers, FileCode2, CircleCheck } from 'lucide-react';
import { useWallet } from '../lib/wallet';
import { abi } from '../lib/collection';
import { CHAIN_ID, EXPLORER, TREASURY, message, sameAddress, shortAddress } from '../lib/config';
import { deployCollection, exportJSON, loadDeploymentFiles, readJournal, saveJournal, verifyRuntime, type Artifacts, type Journal, type Manifest } from '../lib/deployment';
export default function DeployPage(){
 const w=useWallet();const [files,setFiles]=useState<{manifest:Manifest;artifacts:Artifacts}|null>(null);const [journal,setJournal]=useState<Journal|null>(readJournal);
 const [error,setError]=useState('');const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const [address,setAddress]=useState(journal?.collection||'');const [validator,setValidator]=useState('');
 const [info,setInfo]=useState<{owner:string;open:boolean;validator:string;total:number}|null>(null);const lock=useRef(false);
 const isTreasury=sameAddress(w.account,TREASURY);const chunks=files?.manifest.art.flatMap(a=>a.chunks)||[];
 useEffect(()=>{let alive=true;loadDeploymentFiles().then(f=>{if(alive)setFiles(f);}).catch(e=>{if(alive)setError(message(e));});return()=>{alive=false;};},[]);
 async function run(){if(lock.current||!files)return;lock.current=true;setBusy(true);setError('');try{const s=await w.signer();const result=await deployCollection(s,files.manifest,files.artifacts,(j,stage)=>{setJournal(j);setStatus(stage);});setAddress(result.collection);setStatus('Contracts deployed and verified. Open minting when you are ready.');}catch(e){setError(message(e));setJournal(readJournal());}finally{setBusy(false);lock.current=false;}}
 async function read(){setError('');try{if(!files)throw Error('Wait for deployment files to load.');const s=await w.signer();await verifyRuntime(s.provider,address,files.artifacts.HazelsCTOFreemint);const c=new Contract(address,abi,s);const [owner,open,v,total]=await Promise.all([c.owner(),c.mintOpen(),c.getTransferValidator(),c.totalSupply()]);setInfo({owner,open,validator:v,total:Number(total)});}catch(e){setError(message(e));setInfo(null);}}
 async function action(kind:'open'|'close'|'validator'){
  if(lock.current||!files)return;lock.current=true;setBusy(true);setError('');
  try{
   const s=await w.signer();await verifyRuntime(s.provider,address,files.artifacts.HazelsCTOFreemint);const c=new Contract(address,abi,s);
   if(!sameAddress(await c.owner(),await s.getAddress()))throw Error('Connect the current collection owner.');
   if(kind==='validator'&&(!isAddress(validator)||validator===ZeroAddress))throw Error('Enter the supported validator contract for Robinhood Chain.');
   if(kind==='validator'&&await s.provider.getCode(validator)==='0x')throw Error('There is no validator contract at that address on this chain.');
   setStatus('Confirm the collection setting in your wallet.');
   const tx=kind==='validator'?await c.setTransferValidator(validator):await c.setMintOpen(kind==='open');
   setStatus(`Waiting for confirmation: ${tx.hash}`);const r=await tx.wait();if(!r||r.status!==1)throw Error('Transaction did not succeed.');
   setStatus(kind==='validator'?'Validator assigned. Complete its policy and Enforce earnings setup in OpenSea Studio.':'Mint status updated onchain.');await read();
  }catch(e){setError(message(e));}finally{setBusy(false);lock.current=false;}
 }
 async function importProgress(file:File|undefined){if(!file||busy)return;try{const j=JSON.parse(await file.text()) as Journal;if(j.chainId!==CHAIN_ID||!files||j.manifestHash!==files.manifest.manifestHash||!Array.isArray(j.chunks)||!Array.isArray(j.receipts)||!sameAddress(j.deployer,TREASURY))throw Error('This progress file does not match the chain, artwork or treasury.');if(readJournal()?.pending)throw Error('Resolve the current pending transaction before importing another journal.');saveJournal(j);setJournal(j);setAddress(j.collection||'');setStatus('Progress imported. All saved contracts will be verified onchain when resumed.');}catch(e){setError(message(e));}}
 const canManage=info&&sameAddress(info.owner,w.account);
 return <main className="deploy-main"><a className="back-link" href="/">← Back to the collection</a><div className="deploy-heading"><span className="eyebrow">COLLECTION STUDIO</span><h1>Your art.<br/><em>Onchain, forever.</em></h1><p>Deploy the artwork, renderer and collection from your treasury wallet. Each step is saved and checked before the next.</p></div>
 <div className="deploy-layout"><section className="studio-card"><div className="section-label"><Layers size={18}/><span>01 / DEPLOY THE COLLECTION</span></div><h2>One guided flow.</h2><div className="settings-grid"><div><span>COLLECTION</span><strong>Hazels CTO Freemint</strong></div><div><span>SUPPLY</span><strong>5,555 NFTs</strong></div><div><span>PUBLIC MINT</span><strong>Free · 2 per wallet</strong></div><div><span>ROYALTY</span><strong>5% · Treasury receives</strong></div></div><p className="treasury-line"><LockKeyhole size={15}/> Owner & treasury <span className="mono break">{TREASURY}</span></p>
 <div className="deployment-steps">{[
 {title:'Store the character artwork',detail:`${chunks.length||'…'} immutable data contracts`,done:!!chunks.length&&(journal?.chunks.length||0)===chunks.length},
 {title:'Deploy the SVG renderer',detail:'Fixed artwork, traits and rarity',done:!!journal?.renderer},
 {title:'Deploy Hazels CTO Freemint',detail:'5,555 supply · Treasury wallet exception',done:!!journal?.collection},
 ].map((s,i)=><div className={`deployment-step ${s.done?'done':''}`} key={s.title}><span>{s.done?<Check size={16}/>:i+1}</span><div><strong>{s.title}</strong><small>{s.detail}</small></div></div>)}</div>
 <div className="notice">{chunks.length+2} deployment transactions. Your wallet shows the network gas for each. Mint starts closed; opening mint is a separate transaction.</div>
 <button className="primary" disabled={busy||!files||!isTreasury||w.chain!==CHAIN_ID||!!journal?.collection} onClick={run}>{busy?<><LoaderCircle className="spin" size={18}/> Deploying…</>:journal?.collection?<><Check size={18}/> Deployment complete</>:journal?<><ArrowUpRight size={18}/> Resume deployment</>:<>Deploy collection <ArrowUpRight size={18}/></>}</button>
 {!w.account?<p className="small muted">Connect the treasury wallet using the button above.</p>:!isTreasury?<p className="small muted">Deployment is available to treasury {shortAddress(TREASURY)}.</p>:w.chain!==CHAIN_ID?<button className="secondary full" onClick={async()=>{try{await w.switchChain();}catch(e){setError(message(e));}}}>Switch to Robinhood Chain</button>:null}
 <div className="journal-actions">{journal?<button className="text-button" onClick={()=>exportJSON('hazels-deployment-progress.json',journal)}><Download size={14}/> Export progress</button>:null}<label className="text-button file-label">Import progress<input type="file" accept="application/json" disabled={busy} onChange={e=>void importProgress(e.target.files?.[0])}/></label></div>
 {journal?.pending?<a className="transaction-link" href={`${EXPLORER}/tx/${journal.pending.hash}`} target="_blank" rel="noreferrer">View pending transaction <ArrowUpRight size={14}/></a>:null}
 </section><aside className="studio-aside"><div className="studio-art"><img src="/art/characters/3.webp" alt="The original side-braid Hazel with detailed leather jacket"/></div><div className="notice"><CircleCheck size={18}/><div><strong>No keys. No code to paste.</strong><p>You approve transactions in your own wallet. Resume after interruption using this browser or your exported progress file.</p></div></div><a className="text-button" href="/deployment/compiler-input.json" download><FileCode2 size={15}/> Download verification source</a><a className="text-button" href="/deployment/build.json" download>Compiler settings ↗</a></aside></div>
 {status?<p className="notice success break" role="status">{status}</p>:null}{error?<p className="notice error break" role="alert">{error}</p>:null}
 {journal?.collection?<section className="studio-card publish-card"><div className="section-label"><Check size={18}/><span>02 / PUBLISH THE MINT ADDRESS</span></div><h2>Your collection is deployed.</h2><p className="mono break">{journal.collection}</p><div className="button-row"><button className="secondary" onClick={()=>exportJSON('site-config.json',{chainId:CHAIN_ID,collectionAddress:journal.collection})}><Download size={16}/> Download site-config.json</button><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(JSON.stringify({chainId:CHAIN_ID,contractAddress:journal.collection,rendererAddress:journal.renderer,deploymentTxHash:journal.receipts.at(-1),treasury:TREASURY,supply:5555},null,2));setStatus('Deployment details copied.');}catch{setError('Clipboard unavailable. Export the deployment progress instead.');}}}><Copy size={15}/> Copy deployment details</button><a className="text-button" href={`${EXPLORER}/address/${journal.collection}`} target="_blank" rel="noreferrer">View contract ↗</a></div><p className="small muted">Replace <code>public/site-config.json</code> in the repository with the downloaded file and publish the site. The public mint page uses that shared configuration; browser storage does not activate minting for everyone.</p></section>:null}
 <section className="studio-card manage-card"><div className="section-label"><LockKeyhole size={18}/><span>03 / MANAGE MINT & CREATOR EARNINGS</span></div><h2>Launch on your terms.</h2><label htmlFor="collection-address">Collection contract</label><div className="input-button"><input id="collection-address" className="mono" placeholder="0x…" value={address} onChange={e=>{setAddress(e.target.value.trim());setInfo(null);}}/><button className="secondary" disabled={busy||!w.account||!address} onClick={read}>Read contract</button></div>
 {info?<><div className="settings-grid manage-stats"><div><span>MINT</span><strong>{info.open?'Open':'Closed'}</strong></div><div><span>TOTAL MINTED</span><strong>{info.total.toLocaleString()}</strong></div><div><span>TRANSFER VALIDATOR</span><strong>{info.validator===ZeroAddress?'Not configured':shortAddress(info.validator)}</strong></div></div><button className="primary fit" disabled={busy||!canManage} onClick={()=>action(info.open?'close':'open')}>{info.open?'Pause minting':'Open minting'} <ArrowUpRight size={18}/></button><hr/><label htmlFor="validator">OpenSea-supported transfer validator on Robinhood Chain</label><div className="input-button"><input id="validator" className="mono" placeholder="Verified validator contract address" value={validator} onChange={e=>setValidator(e.target.value.trim())}/><button className="secondary" disabled={busy||!canManage||!validator} onClick={()=>action('validator')}>Set validator</button></div>{!canManage?<p className="small muted">Only the current collection owner can change these settings.</p>:null}</>:null}
 <p className="small muted">5% royalty information is built in. Enforcement requires a supported validator deployed on this chain, its transfer policy, and Enforce earnings in OpenSea Studio. Assigning an address alone does not activate enforcement. A validator can restrict transfers, so verify the official deployment first.</p><a className="text-button" href="https://docs.opensea.io/docs/creator-fee-enforcement" target="_blank" rel="noreferrer">OpenSea enforcement guide <ArrowUpRight size={15}/></a>
 </section></main>;
}
