import fs from 'node:fs';
import { keccak256, toUtf8Bytes } from 'ethers';
import solady from 'solady';
import { parts } from './character-art.mjs';
const buffers=[],entries=[];let offset=0,originalBytes=0;
for(const part of parts){
 if (/<(?:image|script|foreignObject)\b|(?:href|src)="(?!#)/i.test(part.svg)) throw Error('External assets forbidden');
 const raw=Buffer.from(part.svg);const hex='0x'+raw.toString('hex');const packed=solady.LibZip.flzCompress(hex);
 if(solady.LibZip.flzDecompress(packed)!==hex)throw Error('Compression mismatch');
 const b=Buffer.from(packed.slice(2),'hex');buffers.push(b);entries.push({name:part.name,offset,length:b.length});offset+=b.length;originalBytes+=raw.length;
}
const bytes=Buffer.concat(buffers),chunks=[];
for(let off=0;off<bytes.length;off+=24000){const chunk=bytes.subarray(off,off+24000);const runtime=Buffer.concat([Buffer.from([0]),chunk]);chunks.push({initCode:'0x61'+runtime.length.toString(16).padStart(4,'0')+'80600a3d393df3'+runtime.toString('hex'),codeHash:keccak256(runtime),bytes:chunk.length});}
const art=[{name:'Hazels modular character atlas',originalBytes,compressedBytes:bytes.length,hash:keccak256(bytes),chunks}];
const manifest={art,parts:entries,manifestHash:keccak256(toUtf8Bytes(JSON.stringify({art,entries})))};
fs.mkdirSync('public/deployment',{recursive:true});fs.writeFileSync('public/deployment/art.json',JSON.stringify(manifest));
const table=entries.map(e=>e.offset.toString(16).padStart(8,'0')+e.length.toString(16).padStart(8,'0')).join('');
fs.writeFileSync('contracts/ArtManifest.sol',`// SPDX-License-Identifier: MIT\npragma solidity 0.8.26;\n// Generated by npm run art. Immutable commitment to every character layer.\nlibrary ArtManifest {\n bytes32 internal constant MANIFEST = ${manifest.manifestHash};\n bytes32 internal constant ATLAS_HASH = ${art[0].hash};\n function entry(uint256 i) internal pure returns(uint256 start,uint256 size){\n  require(i<${entries.length}); bytes memory table=hex"${table}";\n  assembly("memory-safe"){start:=shr(224,mload(add(add(table,32),mul(i,8)))) size:=shr(224,mload(add(add(table,36),mul(i,8))))}\n }\n}\n`);
console.log({atlasBytes:originalBytes,compressedBytes:bytes.length,dataTransactions:chunks.length,parts:entries.length});
