import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, ChevronDown, Flower2, Plus, Sparkles } from 'lucide-react';
import { WalletProvider } from './lib/wallet';
import { EXPLORER, REPO, shortAddress } from './lib/config';
import { loadAddress } from './lib/collection';
import WalletButton from './components/WalletButton';
import MintPanel from './components/MintPanel';
const DeployPage=lazy(()=>import('./components/DeployPage'));
import gallery from './generated/gallery.json';
const faqs=[
 ['Is this really a free mint?','The planned public mint price is 0 ETH with a limit of two NFTs per wallet. Minting is managed through OpenSea; check the published drop settings before signing. Network gas still applies.'],
 ['Will every Hazel be different?','Each of the 5,555 tokens has a distinct combination of an illustrated look, hair palette, outfit palette and background. The three original illustrations keep their faces, hairstyles, clothing details and accessories. These are color compositions of three illustrated looks, not 5,555 separately drawn characters.'],
 ['How does rarity work?','The full collection contains 4,166 Signature, 1,111 Rare and 278 Legendary editions. Character traits and images are available immediately from the metadata server. Allocation follows a public, deterministic formula; this is not a hidden rarity draw.'],
 ['Where is the artwork stored?','Images and metadata are hosted on Vercel using the approved SVG artwork. Each token ID has a fixed image and trait assignment. The domain and hosting must remain available; this collection does not store its artwork onchain.'],
 ['Which network and wallet do I need?','Use an EVM wallet on Robinhood Chain, chain ID 4663, with a little ETH for gas. On mobile, open this page inside your wallet browser.'],
 ['What are the creator earnings?','The planned secondary-sale creator earnings are 5%, payable to the treasury. The collection owner configures and activates enforcement in OpenSea Studio. Metadata alone does not enforce royalties.'],
];
function Collection(){
 const [address,setAddress]=useState('');const [configError,setConfigError]=useState('');
 useEffect(()=>{let live=true;loadAddress().then(a=>{if(live)setAddress(a);}).catch(()=>{if(live)setConfigError('The collection configuration could not be loaded. Please refresh.');});return()=>{live=false;};},[]);
 return <main>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-cross">✳</span> A FREE MINT. A FRESH CHAPTER.</div><h1>A little different.<br/><span>Entirely yours.</span></h1><div className="hero-intro"><p>5,555 characters. One shared spirit.<br/>Meet Hazels CTO Freemint — a collection<br className="desktop-break"/> with a little character in every detail.</p><a className="round-arrow" href="#collection" aria-label="Explore the characters"><ArrowRight size={24}/></a></div><div className="hero-art"><div className="art-stamp"><Flower2 size={28}/><span>INSTANT<br/>REVEAL</span></div><figure className="hero-portrait portrait-left"><img src="/art/characters/1.webp" alt="Hazel with detailed twin buns, a charcoal hoodie and a crossbody buckle"/><figcaption>INDIVIDUALLY YOURS.</figcaption></figure><figure className="hero-portrait portrait-center"><img src="/art/characters/2.webp" alt="Hazel with a chestnut ponytail and indigo denim overalls" fetchPriority="high"/><figcaption>HAZELS CTO / 5,555</figcaption></figure><figure className="hero-portrait portrait-right"><img src="/art/characters/3.webp" alt="Hazel with a side braid, leather jacket and pendant"/><figcaption>MADE TO STAY.</figcaption></figure><span className="art-caption">ONE FACE. THOUSANDS OF WAYS TO BE YOU.</span></div></div><div className="mint-column"><span className="handwritten">Your next chapter starts here ↘</span><MintPanel address={address}/>{configError?<p className="notice error" role="alert">{configError}</p>:null}<div className="mint-footnotes"><span><Plus size={13}/> Instant reveal</span><span><Plus size={13}/> Detailed SVG art</span></div></div></section>
  <div className="collection-strip"><span>5,555 <small>ONE-OF-A-KIND COMBINATIONS</small></span><Flower2 size={22}/><span>0 ETH <small>MINT PRICE</small></span><Flower2 size={22}/><span>100% <small>SVG ART</small></span><Flower2 size={22}/><span>YOURS <small>FROM THE FIRST BLOCK</small></span></div>
  <section className="collection-section" id="collection"><div className="section-heading"><div><span className="eyebrow">SAME SOUL. DIFFERENT ENERGY.</span><h2>A character for<br/><em>every side of you.</em></h2></div><p>Twin buns and a hoodie. A high ponytail and denim. A side braid and leather. Three detailed illustrations, with individual hair, outfit and background palettes.</p></div><div className="gallery">{gallery.map(item=><figure className="gallery-card" key={item.id}><div className="gallery-image"><img src={`/art/characters/${item.id}.webp`} alt={item.alt} loading="lazy"/><span>#{String(item.id).padStart(4,'0')}</span></div><figcaption><strong>{item.name}</strong><small>{item.tag}</small></figcaption></figure>)}</div><div className="trait-totals"><span><strong>3</strong>Illustrated looks</span><span><strong>12</strong>Hair palettes</span><span><strong>16</strong>Outfit palettes</span><span><strong>32</strong>Background palettes</span><span><strong>5,555</strong>Distinct compositions</span></div></section>
  <section className="rarity-section" id="rarity"><div className="rarity-title"><span className="eyebrow">A FEW EXTRA SPARKS.</span><h2>Everyday magic.<br/><em>Extraordinary details.</em></h2><p>Three editions. A fixed place in the collection.<br/>Your traits are revealed the moment you mint.</p><a href="#mint" className="text-button">Find your Hazel <ArrowUpRight size={17}/></a></div><div className="rarity-cards">{[{name:'Signature',count:'4,166',p:'74.996%',cls:'signature',icon:'01'},{name:'Rare',count:'1,111',p:'20%',cls:'rare',icon:'02'},{name:'Legendary',count:'278',p:'5.004%',cls:'legendary',icon:'03'}].map(r=><div className={`rarity-card ${r.cls}`} key={r.name}><span>{r.icon} / EDITION</span><div className="rarity-symbol"><Sparkles size={46} strokeWidth={1}/></div><h3>{r.name}</h3><div><strong>{r.count}</strong><small>{r.p} of the collection</small></div></div>)}</div></section>
  <section className="faq-section" id="details"><div><span className="eyebrow">GOOD TO KNOW.</span><h2>The little<br/><em>details.</em></h2><p>Simple mint. Lasting artwork.</p>{address?<a className="contract-link" href={`${EXPLORER}/address/${address}`} target="_blank" rel="noreferrer">Contract {shortAddress(address)} <ArrowUpRight size={14}/></a>:<span className="small muted">Contract address will appear after deployment.</span>}</div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>
  <section className="closing"><Flower2 size={36}/><p>Make room for a little character.</p><a href="#mint">Find your Hazel <ArrowUpRight size={21}/></a></section>
 </main>;
}
export default function App(){const deploy=window.location.pathname.replace(/\/$/,'')==='/deploy';return <WalletProvider><div className="site-shell"><header className="site-header"><a href="/" className="brand" aria-label="Hazels CTO home"><span className="brand-mark">H</span><span>hazels<small>CTO FREEMINT</small></span></a><nav aria-label="Main navigation"><a href="/#collection">The collection</a><a href="/#rarity">Rarity</a><a href="/#details">The details</a></nav><WalletButton/></header><Suspense fallback={<div className="page-loading" role="status">Opening collection studio…</div>}>{deploy?<DeployPage/>:<Collection/>}</Suspense><footer><a className="footer-brand" href="/">hazels<span>CTO FREEMINT</span></a><span>Art with a home on Robinhood Chain.</span><div><a href={REPO} target="_blank" rel="noreferrer">Source ↗</a><a href="/deploy">Metadata studio ↗</a></div></footer></div></WalletProvider>;}
