import {lazy, Suspense} from 'react';
import {Plus, Star, BookOpen, ChevronDown} from 'lucide-react';
import './anime.css';
const DeployPage=lazy(()=>import('./components/DeployPage'));
const OPENSEA='https://opensea.io/collection/hazels-cto-freemint/overview';
const EXPLORER='https://robinhoodchain.blockscout.com/address/0x06886656be382935137ad4E8B9Ef75194BD5bD03';
const characters=[
 {id:1,no:'01',name:'After hours.',look:'Ink hoodie',detail:'Twin buns. Oversized hoodie. A world of her own.'},
 {id:2,no:'02',name:'Daydream believer.',look:'Indigo denim',detail:'High ponytail. Favorite denim. Somewhere to be.'},
 {id:3,no:'03',name:'Wild at heart.',look:'Braided leather',detail:'Side braid. Leather jacket. Her own way home.'},
];
const faqs=[
 ['Where do I mint?','Mint through our Hazels CTO Freemint collection on OpenSea. Use any Mint on OpenSea button on this page. This website does not ask you to connect a wallet or sign a transaction.'],
 ['What makes each Hazel different?','5,555 distinct compositions combine three detailed illustrated looks with 12 hair palettes, 16 outfit palettes and 32 background settings. Faces, hairstyles, clothing details and accessories stay faithful to the original illustrations.'],
 ['When will I see my character?','Each minted token points directly to its SVG portrait and traits through our metadata server. OpenSea may take a little time to index a new mint.'],
 ['Where does the artwork live?','Your NFT lives on Robinhood Chain. The SVG artwork and metadata are hosted on Vercel under this domain, with a fixed assignment for each token ID. All 5,555 assignments are public.'],
 ['How do editions work?','The collection includes 4,166 Signature, 1,111 Rare and 278 Legendary editions. Edition is a metadata trait; it does not add a frame or change the character drawing.'],
];
function MintLink({className='manga-button'}:{className?:string}){return <a href={OPENSEA} className={className} target="_blank" rel="noreferrer">Mint on OpenSea</a>;}
function Landing(){return <main>
 <section className="manga-hero" aria-labelledby="hero-title"><div className="hero-edition"><span>HAZELS CTO FREEMINT</span><span>ISSUE 001 · THE BEGINNING</span></div><div className="manga-hero-grid">
  <div className="manga-intro"><div className="chapter-label"><span/> A NEW CHAPTER ON ROBINHOOD</div><h1 id="hero-title">Your story.<br/>Your <em>Hazel.</em></h1><p>5,555 anime portraits.<br/>A little attitude. A world of possibility.</p><div className="hero-actions"><MintLink/><a className="manga-text-link" href="#characters">Meet the characters <ChevronDown size={17}/></a></div><div className="hero-facts"><div><strong>5,555</strong><span>Total supply</span></div><div><strong>FREE</strong><span>Mint + network gas</span></div><div><strong>01</strong><span>Your next chapter</span></div></div></div>
  <div className="manga-art" aria-label="Three original Hazel characters"><div className="art-sun"/><div className="art-speckles"/><span className="hand-note">Every face has a story.</span><figure className="manga-panel panel-back"><img src="/art/characters/3.webp" alt="Side-braid Hazel wearing a leather jacket" width="600" height="600"/><span>THE WILD ONE</span></figure><figure className="manga-panel panel-front"><img src="/art/characters/1.webp" alt="Hazel with twin buns, a charcoal hoodie and a crossbody buckle" width="600" height="600" fetchPriority="high"/><span>THE WORLD IS YOURS.</span></figure><figure className="manga-panel panel-small"><img src="/art/characters/2.webp" alt="Ponytail Hazel in indigo denim overalls" width="600" height="600"/><span>JUST BE YOU.</span></figure><div className="art-seal"><Star size={26}/><strong>FREE<br/>MINT</strong></div><span className="panel-caption">PORTRAITS OF POSSIBILITY / 5,555 EDITIONS</span></div>
 </div></section>
 <div className="manga-strip" aria-label="Collection details"><span>HAZELS CTO</span><Star size={20}/><span>5,555 PORTRAITS</span><Star size={20}/><span>ROBINHOOD CHAIN</span><Star size={20}/><span>INSTANT REVEAL</span><Star size={20}/><span>MAKE IT YOURS</span></div>
 <section className="manga-characters" id="characters"><div className="manga-section-heading"><div><span className="section-number">01 / MEET THE CAST</span><h2>Three looks.<br/><em>A thousand moods.</em></h2></div><p>The quiet ones. The daydreamers. The ones who take the long way home.<br/><strong>There’s a little Hazel in all of us.</strong></p></div><div className="character-panels">{characters.map(c=><figure className="character-panel" key={c.id}><div className="character-image"><img src={`/art/characters/${c.id}.webp`} alt={c.detail} width="600" height="600" loading="lazy"/><span className="character-index">{c.no}</span><span className="character-look">{c.look}</span></div><figcaption><h3>{c.name}</h3><p>{c.detail}</p></figcaption></figure>)}</div><div className="palette-note"><BookOpen size={24}/><p><strong>The details make the difference.</strong> 12 hair palettes. 16 outfit palettes. 32 background settings. 5,555 individual compositions.</p><a className="manga-text-link" href={OPENSEA} target="_blank" rel="noreferrer">Explore on OpenSea</a></div></section>
 <section className="manga-editions" id="editions"><div className="edition-intro"><span className="section-number">02 / FIND YOUR EDITION</span><h2>A familiar face.<br/><em>A different kind of rare.</em></h2><p>Three editions, woven through the collection.</p></div><div className="edition-list">{[{name:'Signature',n:'4,166',p:'74.996%'},{name:'Rare',n:'1,111',p:'20%'},{name:'Legendary',n:'278',p:'5.004%'}].map((r,i)=><div className={'edition-row edition-'+i} key={r.name}><span className="edition-symbol">{i===0?<Plus/>:i===1?<Star/>:<><Star/><Star/></>}</span><h3>{r.name}</h3><div><strong>{r.n}</strong><span>{r.p} of the collection</span></div></div>)}</div></section>
 <section className="manga-faq" id="details"><div><span className="section-number">03 / BEFORE YOUR CHAPTER</span><h2>A few<br/><em>little details.</em></h2><span className="faq-doodle" aria-hidden="true">?</span></div><div className="manga-questions">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div></section>
 <section className="manga-ending"><div className="ending-top"><span>THIS IS WHERE YOUR STORY BEGINS.</span><Star size={26}/><span>HAZELS CTO FREEMINT</span></div><h2>Main character.<br/><em>Your call.</em></h2><MintLink className="manga-button light-button"/><div className="ending-rule"><span>5,555 HAZELS. ONE SHARED WORLD.</span><span>SEE YOU ON THE OTHER SIDE.</span></div></section>
 </main>;}
export default function App(){const studio=window.location.pathname.replace(/\/$/,'')==='/deploy';return <div className="anime-site"><header className="manga-header"><a className="manga-brand" href="/" aria-label="Hazels CTO home">hazels<span>CTO FREEMINT</span></a><nav aria-label="Main navigation"><a href="/#characters">The cast</a><a href="/#editions">Editions</a><a href="/#details">Details</a></nav><MintLink className="header-mint"/></header><Suspense fallback={<div className="page-loading" role="status">Opening metadata studio…</div>}>{studio?<DeployPage/>:<Landing/>}</Suspense><footer className="manga-footer"><a className="manga-brand" href="/">hazels<span>YOUR STORY STARTS HERE.</span></a><p>Hazels CTO Freemint · Robinhood Chain</p><div><a href={OPENSEA} target="_blank" rel="noreferrer">OpenSea</a><a href={EXPLORER} target="_blank" rel="noreferrer">Contract</a><a href="/deploy">Metadata</a></div></footer></div>;}
